# Generated by Django 6.0 on 2026-01-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(editable=False)),
                ('survey_answers', models.JSONField()),
                ('followup_answers', models.JSONField()),
                ('recommended_chapters', models.JSONField()),
                ('chat_ids', models.JSONField()),
                ('agent_scratchpad', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
