# Generated by Django 6.0 on 2026-01-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_scratchpad',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='followup_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='recommended_chapters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='survey_answers',
            field=models.JSONField(default=dict),
        ),
    ]
