# Generated by Django 6.0 on 2026-02-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_agent_scratchpad_alter_user_chat_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followup_questions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_user_id",
            field=models.CharField(blank=True, editable=False),
        ),
    ]
